- name: create new vpc,print details and save in new variable
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: include variables
    include_vars: vpc_var

  - name: create vpc
    ec2_vpc_net:
      name: "{{vpc_name}}"
      cidr_block: "{{vpc_cidr_block}}"
      region: "{{region}}"
      dns_support: yes
      dns_hostnames: yes
      state: "{{state}}"
    register: vpc_out

  - name: print vpc details
    debug:
      var: vpc_out

  - name: create public sub1 in zone1
    ec2_vpc_subnet:
      vpc_id: "{{vpc_out.vpc.id}}"
      region: "{{region}}"
      az: "{{zone1}}"
      cidr: "{{pubsub1cidr}}"
      map_public: yes
      state: "{{state}}"
      tags:
        Name: anilprofile_publicsubnet1
    register: public_sub1_out

  - name: print subnet details
    debug: 
      var: public_sub1_out

  - name: create public sub2 in zone2
    ec2_vpc_subnet:
      vpc_id: "{{vpc_out.vpc.id}}"
      region: "{{region}}"
      az: "{{zone2}}"
      cidr: "{{pubsub2cidr}}"
      map_public: yes
      state: "{{state}}"
      tags:
        Name: anilprofile_publicsubnet2
    register: public_sub2_out

  - name: print subnet details
    debug:
      var: public_sub2_out

  - name: create public sub3 in zone3
    ec2_vpc_subnet:
      vpc_id: "{{vpc_out.vpc.id}}"
      region: "{{region}}"
      az: "{{zone3}}"
      cidr: "{{pubsub3cidr}}"
      map_public: yes
      state: "{{state}}"
      tags:
        Name: anilprofile_publicsubnet3
    register: public_sub3_out

  - name: print subnet details
    debug:
      var: public_sub3_out
  
  - name: create private sub1 in zone1
    ec2_vpc_subnet:
      vpc_id: "{{vpc_out.vpc.id}}"
      region: "{{region}}"
      az: "{{zone1}}"
      cidr: "{{pvtsub1cidr}}"
      state: "{{state}}"
      tags:
        Name: anilprofile_privatesubnet1
    register: private_sub1_out

  - name: print subnet details
    debug:
      var: private_sub1_out

  - name: create private sub2 in zone2
    ec2_vpc_subnet:
      vpc_id: "{{vpc_out.vpc.id}}"
      region: "{{region}}"
      az: "{{zone2}}"
      cidr: "{{pvtsub2cidr}}"
      state: "{{state}}"
      tags:
        Name: anilprofile_privatesubnet2
    register: private_sub2_out

  - name: print subnet details
    debug:
      var: private_sub2_out

  - name: create private sub3 in zone3
    ec2_vpc_subnet:
      vpc_id: "{{vpc_out.vpc.id}}"
      region: "{{region}}"
      az: "{{zone3}}"
      cidr: "{{pvtsub3cidr}}"
      map_public: yes
      state: "{{state}}"
      tags:
        Name: anilprofile_privatesubnet3
    register: private_sub3_out

  - name: print subnet details
    debug:
      var: private_sub3_out

  - name: create internet gateway
    ec2_vpc_igw:
      vpc_id: "{{vpc_out.vpc.id}}"
      region: "{{region}}"
      state: "{{state}}"
      tags:
        Name: anilprofile_internet_gate_way
    register: igw_out

  - name: print igw details
    debug:
      var: igw_out

  - name: create and assign routtable to internet gate way
    ec2_vpc_route_table:
      vpc_id: "{{vpc_out.vpc.id}}"
      region: "{{region}}"
      state: "{{state}}"
      tags:
        Name: anilprofile_igw_routetable
      subnets:
        - "{{public_sub1_out.subnet.id}}"
        - "{{public_sub2_out.subnet.id}}"
        - "{{public_sub3_out.subnet.id}}"
      routes:
        - dest: 0.0.0.0/0
          gateway_id: "{{igw_out.gateway_id}}"
    register: pub_routetable_out

  - name: print public routetable details
    debug:
      var: pub_routetable_out
  
  - name: create internet nat gateway
    ec2_vpc_nat_gateway:
      subnet_id: "{{public_sub1_out.subnet.id}}"
      region: "{{region}}"
      state: "{{state}}"
      wait: yes
      if_exist_do_not_create: true
    register: nat_gate_way_out

  - name: print nat gate way details
    debug:
      var: nat_gate_way_out

  - name: create and assign route table to nat gate way
    ec2_vpc_route_table:
      vpc_id: "{{vpc_out.vpc.id}}"
      region: "{{region}}"
      state: "{{state}}"
      tags:
        Name: anilprofile_pvt_routetable
      subnets:
        - "{{private_sub1_out.subnet.id}}"
        - "{{private_sub2_out.subnet.id}}"
        - "{{private_sub3_out.subnet.id}}"
      routes:
        - dest: 0.0.0.0/0
          gateway_id: "{{nat_gate_way_out.nat_gateway_id}}"
    register: pvt_routetable_out

  - name: print private routetable details
    debug:
      var: pvt_routetable_out


  - debug:
      var: "{{item}}"
    loop:
      - vpc_out.vpc.id
      - public_sub1_out.subnet.id
      - public_sub2_out.subnet.id
      - public_sub3_out.subnet.id
      - private_sub1_out.subnet.id
      - private_sub2_out.subnet.id
      - private_sub3_out.subnet.id
      - igw_out.gateway_id
      - pub_routetable_out.route_table.id
      - nat_gate_way_out.nat_gateway_id
      - pvt_routetable_out.route_table.id 
  
  - name: copy var to file
    copy:
      content: "vpc_id: {{vpc_out.vpc.id}}\npubsub1id: {{public_sub1_out.subnet.id}}\npubsub2id: {{public_sub2_out.subnet.id}}\npubsub3id: {{public_sub3_out.subnet.id}}\npvtsub1id: {{private_sub1_out.subnet.id}}\npvtsub2id: {{private_sub2_out.subnet.id}}\npvtsub3id: {{private_sub3_out.subnet.id}}\nigw_id: {{igw_out.gateway_id}}\npubRT: {{pub_routetable_out.route_table.id}}\nnatgatewayid: {{nat_gate_way_out.nat_gateway_id}}\npvtRT: {{pvt_routetable_out.route_table.id}}\n"
      dest: vpc_setup_output_vars




