- name: vpc creation and print vpc id
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
  - name: include variables from file
    include_vars: vpc_var
    #register: my_var

    #  - name: print varibales
    # debug:
    #  var: my_var
  - name: create my vpc
    ec2_vpc_net:
      name: "{{vpc_name}}"
      cidr_block: "{{vpc_cidr_block}}"
      region: "{{region}}"
      dns_support: yes
      dns_hostnames: yes
      tenancy: default
      state: "{{state}}"
    register: vpc_out

  - name: print vpc details
    debug:
      var: vpc_out
  - name: save vpc id in variable file
    copy: 
      content: "vpc_id: {{vpc_out.vpc.id}}"
      dest: new_var
